# Generated by Django 5.0.3 on 2024-05-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hospital',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='specialisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.specialisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
