# Generated by Django 5.0.3 on 2024-05-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_room_hospital_appointment_appt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
