# Generated by Django 5.0.3 on 2024-05-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_appointment_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='fname',
        ),
    ]
